### ISSUE TITLE
org.springframework:spring-web not optional

### ISSUE THREAD

**Issue by joschuck** [taskadapter/trello-java-wrapper#10]
I could not use the wrapper without adding `org.springframework:spring-web` to my build.gradle.

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/web/client/RestClientException
    at com.julienvey.trello.impl.TrelloImpl.<init>(TrelloImpl.java:27)
    at de.joschuck.Main.main(Main.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.springframework.web.client.RestClientException
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 7 more
```

Is it optional and I am just missing something?

**Comment by simonbasle** [comment]
Looks like the lib knows how to use 3 different http clients. In case you happen to have one of them already in your project, you can simply use the corresponding implementation without trello wrapper pulling the others. But if you have no httpclient in your classpath, you have to choose one and add the dependency explicitely in your pom/build.gradle.

**Comment by simonbasle** [comment]
@haklop @julienvey the README is outdated as a consequence

**Comment by joschuck** [comment]
Ok, thanks!

**Comment by simonbasle** [comment]
added instructions in the Readme
