### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/NestedRuntimeException

### ISSUE THREAD

**Issue by BlaBlaJ** [taskadapter/trello-java-wrapper#11]
Hi Guys, hi @haklop and @julienvey , I using Eclipse and m2e... I added trello-java-wrapper on maven then it uploaded every dependency and library into the path... I made a simple class that implement Trello interface, I instantiated my trelloKey and my trelloAccessToken, then I run this class but eclipse not compile it and generate this error:

Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/NestedRuntimeException
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at com.julienvey.trello.impl.TrelloImpl.<init>(TrelloImpl.java:27)
    at webOnEclipse.UP.main(UP.java:29)
Caused by: java.lang.ClassNotFoundException: org.springframework.core.NestedRuntimeException
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 14 more

What I do for using this trello wrapper?
Is it working or I must remove some stuff on FIX ME into the library classes?

Thanks Men!!

**Comment by BlaBlaJ** [comment]
@nilsga @alecharp @edralzar

**Comment by simonbasle** [comment]
@BlaBlaJ would it happen to be the same error as in #10 ? that is, you need to choose one of the 3 supported Http clients libraries and add it to your dependencies?

**Comment by BlaBlaJ** [comment]
@simonbasle thank you!! How can I make this action?
so, I added apache http client but not working again
...also adding async-http-client not working...i don't know how use this wrapper :')

**Comment by BlaBlaJ** [comment]
must added spring web 4.2.4 then the library worked!

**Comment by simonbasle** [comment]
added instructions in the Readme
