### ISSUE TITLE
Proxy setting

### ISSUE THREAD

**Issue by omzevr** [taskadapter/trello-java-wrapper#19]
Please, I need to connect using proxy setting.

I used as follow, but it didn't work

		Properties props = System.getProperties();
		props.put("http.proxyHost", "server");
		props.put("http.proxyPort", "port");

The error is:

```
18:58:02.041 [main] DEBUG com.julienvey.trello.impl.TrelloImpl - Get request on Trello API at url https://api.trello.com/1/boards/{boardId}?key={applicationKey}&token={userToken} for class com.julienvey.trello.domain.Board with params [EDITED]
Exception in thread "main" com.julienvey.trello.exception.TrelloHttpException: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.trello.com/1/boards/EDITED?key=EDITED&token=EDITED":Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
	at com.julienvey.trello.impl.http.RestTemplateHttpClient.get(RestTemplateHttpClient.java:44)
	at com.julienvey.trello.impl.TrelloImpl.get(TrelloImpl.java:323)
	at com.julienvey.trello.impl.TrelloImpl.getBoard(TrelloImpl.java:40)
	at com.everis.ogmz.main.Principal.main(Principal.java:81)
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.trello.com/1/boards/EDITED?key=EDITED&token=EDITED":Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:498)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:446)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:214)
	at com.julienvey.trello.impl.http.RestTemplateHttpClient.get(RestTemplateHttpClient.java:42)
	... 3 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:656)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:46)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:49)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:483)
	... 6 more
```

**Comment by simonbasle** [comment]
You need to configure the proxy for `https` as well:

```
props.put("https.proxyHost", "server");
props.put("https.proxyPort", "portHttps");
```

**Comment by omzevr** [comment]
Hi,

Thank for you answer, It's working fine right now,

Regards,

Omar
