### ISSUE TITLE
ClassNotFoundException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException

### ISSUE THREAD

**Issue by shamal** [taskadapter/trello-java-wrapper#26]
Initialized the project as per the README. Used spring-web 5.0.1. Still get the error:

`Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/InvalidDefinitionException
	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:73)
	at org.springframework.web.client.RestTemplate.<init>(RestTemplate.java:171)
	at com.julienvey.trello.impl.http.RestTemplateHttpClient.<init>(RestTemplateHttpClient.java:17)
	at com.julienvey.trello.impl.TrelloImpl.<init>(TrelloImpl.java:27)
	at com.shamalk.webchecker.TrelloTest.main(TrelloTest.java:14)`

**Comment by alexeyOnGitHub** [comment]
I see this class is present in Jackson databind exc dependency starting with version 2.9
https://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/exc/InvalidDefinitionException.html
You will need to import that dependency
