### ISSUE TITLE
Can't create label using this wrapper?

### ISSUE THREAD

**Issue by vitaliypo** [taskadapter/trello-java-wrapper#43]
Hi,
I can't find any possibility to add new labels to a board. Was it implemented?
Looks like it's available via official API: https://developers.trello.com/v1.0/reference#page-1

**Comment by alexeyOnGitHub** [comment]
have you tried 
```
addLabelsToCard(String idCard, String[] labels)
```
?

**Comment by vitaliypo** [comment]
Hmm. I've just tried it, but got NPE:
```
Exception in thread "main" java.lang.NullPointerException
	at com.julienvey.trello.impl.http.ApacheHttpClient.postForLocation(ApacheHttpClient.java:108)
	at com.julienvey.trello.impl.TrelloImpl.postForLocation(TrelloImpl.java:498)
	at com.julienvey.trello.impl.TrelloImpl.addLabelsToCard(TrelloImpl.java:461)
	at TestTrelloApi.main(TestTrelloApi.java:70)
```
I see that I get 400 response ("Bad Request") because there's no necessary parameters in request:
`https://api.trello.com/1/cards/x/labels?key=y&token=z`
While there should be also **color** and **name** parameters according to the link: https://developers.trello.com/reference/#cardsidlabels

It looks like I use wrong parameters when calling addLabelsToCard() method, but I can't understand what exactly is wrong:
```
String labs[] = {"testlabel1", "testlabel2"};
var postedcard = trelloApi.createCard(sentListId, card);
trelloApi.addLabelsToCard(postedcard.getId(), labs);
```
By the way, how to specify color for labels using this method?

**Comment by alexeyOnGitHub** [comment]
I have not used labels myself and I won't be able to dedicate much time to this any time soon. you are welcome to investigate this and add proper error handling and parameters check. if you submit a PR, please also provide tests for the changes. I can review it

**Comment by vitaliypo** [comment]
OK, maybe I will find some time to dig in it.

**Comment by nstdio** [comment]
@vitaliypo After merging #60 you may look on [this](https://github.com/taskadapter/trello-java-wrapper/pull/60/files#diff-6e4d1292c90885a82d6260ab02631553R181).

**Comment by vitaliypo** [comment]
@nstdio I've fetched 0.12 version but it did not resolve this issue.
```java 
ApacheHttpClient trelloHttpClient = new ApacheHttpClient();
        Trello trelloApi = new TrelloImpl(properties.getProperty("trello.applicationkey"),
                properties.getProperty("trello.accesstoken"),
                trelloHttpClient);
        Card card = new Card();
        card.setName("Testcard1");
        card.setDesc("Testdesc1");
        Label label = new Label();
        label.setName("Testlabel").setColor("black").setId(properties.getProperty("trello.boardrealid"));
        trelloApi.createLabel(label);
```
Last line gives me a TrelloBadRequestException: Invalid id
```
com.julienvey.trello.TrelloBadRequestException: Invalid id

	at com.julienvey.trello.impl.http.ApacheHttpClient.getEntityAndReleaseConnection(ApacheHttpClient.java:134)
	at com.julienvey.trello.impl.http.ApacheHttpClient.postForObject(ApacheHttpClient.java:61)
	at com.julienvey.trello.impl.TrelloImpl.postForObject(TrelloImpl.java:547)
	at com.julienvey.trello.impl.TrelloImpl.createLabel(TrelloImpl.java:387)
	at TestUtils.TestAddLabel(TestUtils.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
POST request doesn't have any parameters:
```https://api.trello.com/1/labels?key=XXX&token=YYY```
As I see from API doc, it should pass more parameters: https://developers.trello.com/reference/#page-1
```  --url 'https://api.trello.com/1/labels?name=name&color=color&idBoard=idBoard&key=XXX&token=YYY'```

**Comment by nstdio** [comment]
@vitaliypo The problem is with `boardId` you setting `properties.getProperty("trello.boardrealid")` as an id to label. You should do:

```java
Label label = new Label();
label.setName("Testlabel").setColor("black").setIdBoard(properties.getProperty("trello.boardrealid"));
trelloApi.createLabel(label);
```
It should work like that.

**Comment by vitaliypo** [comment]
@nstdio indeed. Label created successfully.
Though it's still impossible to add it to cards, which I initially meant when created this issue. :)

**Comment by nstdio** [comment]
@vitaliypo got it! Seems [here](https://developers.trello.com/v1.0/reference#cardsididlabels) is what you are seeking.

**Comment by vitaliypo** [comment]
@nstdio yes, this one could work. :)
Though I already use another one in my project - [Add a new label to card](https://developers.trello.com/v1.0/reference#cardsidlabels) and it successfully assigns already existing labels as well.

**Comment by nstdio** [comment]
@vitaliypo Although it would be much more elegant and readable to have code like:

```java
Label label = new Label()
    .setInternalTrello(trello)
    .setColor("green")
    .setName("Label")
    .create()
    .addToCard("cardId");
```

**Comment by nstdio** [comment]
@vitaliypo #65
